#ifndef _PLUGINMANAGERVERSION_H
#define _PLUGINMANAGERVERSION_H

  <<<<<<< rename_vs
#define PLUGINMANAGERVERSION_STRING				"1.4.3.0"
#define PLUGINMANAGERVERSION_RESOURCE			1,4,3,0
#define PLUGINMANAGERVERSION_RESOURCE_STRING	"1, 4, 3, 0"
#define PLUGINMANAGERVERSION_RELEASEDATE        "October 2016"
  =======
#define PLUGINMANAGERVERSION_STRING				"1.4.12.0"
#define PLUGINMANAGERVERSION_RESOURCE			1,4,12,0
#define PLUGINMANAGERVERSION_RESOURCE_STRING	"1, 4, 12, 0"
#define PLUGINMANAGERVERSION_RELEASEDATE        "Sep 2018"
  >>>>>>> x64

#endif
